version: 2
updates:
  # .NET NuGet packages
  - package-ecosystem: "nuget"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "dotnet"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "KenyBoi"
    assignees:
      - "KenyBoi"
    # Security updates - apply ASAP
    allow:
      - dependency-type: "all"
    # Automatically rebase PRs when base branch updates
    rebase-strategy: "auto"
    # Ignore specific packages that need manual review
    ignore:
      # Wait for stable .NET 9 LTS before upgrading
      - dependency-name: "Microsoft.AspNetCore.*"
        update-types: ["version-update:semver-major"]
      # Binance.Net major version needs breaking change review
      - dependency-name: "Binance.Net"
        update-types: ["version-update:semver-major"]
    groups:
      microsoft-packages:
        patterns:
          - "Microsoft.*"
        update-types:
          - "minor"
          - "patch"
      testing-packages:
        patterns:
          - "xunit*"
          - "Moq"
          - "FluentAssertions"
        update-types:
          - "minor"
          - "patch"
      broker-packages:
        patterns:
          - "Binance.Net"
          - "Bybit.Net"
        update-types:
          - "minor"
          - "patch"
      security-updates:
        patterns:
          - "*"
        update-types:
          - "patch"

  # npm packages (Frontend)
  - package-ecosystem: "npm"
    directory: "/docs/design/algotrendy_browser_figma"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "frontend"
      - "javascript"
    commit-message:
      prefix: "chore"
    rebase-strategy: "auto"
    versioning-strategy: "increase"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
    groups:
      react-packages:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      radix-ui:
        patterns:
          - "@radix-ui/*"
        update-types:
          - "minor"
          - "patch"

  # npm packages (Frontend - Main)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "frontend"
      - "javascript"
    commit-message:
      prefix: "chore"
    rebase-strategy: "auto"
    versioning-strategy: "increase"
    groups:
      react-packages:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      vite-packages:
        patterns:
          - "vite*"
          - "@vitejs/*"
        update-types:
          - "minor"
          - "patch"

  # Python packages (Backtesting Service)
  - package-ecosystem: "pip"
    directory: "/backtesting-py-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
      - "python"
      - "backtesting"
    commit-message:
      prefix: "chore"
    rebase-strategy: "auto"
    groups:
      data-science-packages:
        patterns:
          - "pandas"
          - "numpy"
          - "scikit-learn"
        update-types:
          - "minor"
          - "patch"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    target-branch: "main"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "docker"
    directory: "/docs/design/algotrendy_browser_figma"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    target-branch: "main"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "docker"
    directory: "/backtesting-py-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    target-branch: "main"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
