import { useState } from 'react';

// Demo data generator for Algolia search testing
const DEMO_TRADES = [
    {
        objectID: '1',
        symbol: 'BTCUSDT',
        strategy: 'momentum',
        entry_price: 65000,
        current_price: 66500,
        quantity: 0.15,
        side: 'long',
        pnl: 225.0,
        pnl_percent: 2.31,
        confidence: 0.85,
        risk_score: 0.35,
        volatility: 0.15,
        stop_loss: 63500,
        take_profit: 68000,
        max_drawdown: 1.2,
        ai_insight: 'Strong upward momentum detected with high volume confirmation',
        ai_generated: true,
        is_live: true,
        market_conditions: ['bull_market', 'high_volume', 'trending_up'],
        created_at: '2024-01-15T10:30:00Z',
        updated_at: '2024-01-15T14:22:00Z',
    },
    {
        objectID: '2',
        symbol: 'ETHUSDT',
        strategy: 'rsi',
        entry_price: 2450,
        current_price: 2380,
        quantity: 1.5,
        side: 'short',
        pnl: -105.0,
        pnl_percent: -2.86,
        confidence: 0.72,
        risk_score: 0.55,
        volatility: 0.22,
        stop_loss: 2520,
        take_profit: 2300,
        max_drawdown: 3.1,
        ai_insight: 'RSI overbought signal confirmed, expecting correction',
        ai_generated: true,
        is_live: true,
        market_conditions: ['overbought', 'resistance_level', 'volume_declining'],
        created_at: '2024-01-15T09:15:00Z',
        updated_at: '2024-01-15T14:20:00Z',
    },
    {
        objectID: '3',
        symbol: 'ADAUSDT',
        strategy: 'macd',
        entry_price: 0.485,
        current_price: 0.520,
        quantity: 2000,
        side: 'long',
        pnl: 70.0,
        pnl_percent: 7.22,
        confidence: 0.91,
        risk_score: 0.25,
        volatility: 0.18,
        stop_loss: 0.460,
        take_profit: 0.550,
        max_drawdown: 0.8,
        ai_insight: 'MACD golden cross with strong volume, continuation likely',
        ai_generated: false,
        is_live: false,
        market_conditions: ['golden_cross', 'breakout', 'high_volume'],
        created_at: '2024-01-14T16:45:00Z',
        updated_at: '2024-01-15T11:30:00Z',
    },
    {
        objectID: '4',
        symbol: 'SOLUSDT',
        strategy: 'bollinger_bands',
        entry_price: 95.50,
        current_price: 92.80,
        quantity: 10,
        side: 'long',
        pnl: -27.0,
        pnl_percent: -2.83,
        confidence: 0.68,
        risk_score: 0.45,
        volatility: 0.31,
        stop_loss: 90.00,
        take_profit: 105.00,
        max_drawdown: 4.2,
        ai_insight: 'Oversold bounce expected from lower Bollinger Band',
        ai_generated: true,
        is_live: true,
        market_conditions: ['oversold', 'support_level', 'low_volume'],
        created_at: '2024-01-15T08:00:00Z',
        updated_at: '2024-01-15T14:18:00Z',
    },
    {
        objectID: '5',
        symbol: 'XRPUSDT',
        strategy: 'vwap',
        entry_price: 0.62,
        current_price: 0.64,
        quantity: 1500,
        side: 'long',
        pnl: 30.0,
        pnl_percent: 3.23,
        confidence: 0.79,
        risk_score: 0.38,
        volatility: 0.19,
        stop_loss: 0.58,
        take_profit: 0.68,
        max_drawdown: 1.5,
        ai_insight: 'Price holding above VWAP with institutional support',
        ai_generated: false,
        is_live: false,
        market_conditions: ['above_vwap', 'institutional_buying', 'steady_volume'],
        created_at: '2024-01-14T14:20:00Z',
        updated_at: '2024-01-15T10:45:00Z',
    },
    {
        objectID: '6',
        symbol: 'DOGEUSDT',
        strategy: 'momentum',
        entry_price: 0.085,
        current_price: 0.091,
        quantity: 10000,
        side: 'long',
        pnl: 60.0,
        pnl_percent: 7.06,
        confidence: 0.73,
        risk_score: 0.62,
        volatility: 0.45,
        stop_loss: 0.080,
        take_profit: 0.095,
        max_drawdown: 2.8,
        ai_insight: 'Meme coin momentum spike, high volatility expected',
        ai_generated: true,
        is_live: true,
        market_conditions: ['momentum_spike', 'high_volatility', 'social_buzz'],
        created_at: '2024-01-15T11:30:00Z',
        updated_at: '2024-01-15T14:15:00Z',
    },
];

export function useDemoSearchClient() {
    const [isDemo, setIsDemo] = useState(true);

    const demoSearchClient = {
        search: (requests: any[]) => {
            return Promise.resolve({
                results: requests.map(() => ({
                    hits: DEMO_TRADES,
                    nbHits: DEMO_TRADES.length,
                    page: 0,
                    nbPages: 1,
                    hitsPerPage: 20,
                    exhaustiveNbHits: true,
                    exhaustiveTypo: true,
                    exhaustive: { nbHits: true, typo: true },
                    query: '',
                    params: '',
                    processingTimeMS: Math.floor(Math.random() * 50) + 10, // Random 10-60ms
                })),
            });
        },
        appId: 'demo-app-id',
        transporter: {} as any,
        addAlgoliaAgent: () => { },
        destroy: () => { },
    };

    return {
        searchClient: demoSearchClient,
        isDemo,
        setIsDemo,
        demoTrades: DEMO_TRADES,
    };
}

export { DEMO_TRADES };