name: Bug Report
description: Report a bug in AlgoTrendy
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Trading Engine
        - Data Channels
        - Brokers
        - Strategies
        - API
        - Backtesting
        - Frontend
        - Infrastructure
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: AlgoTrendy version
      placeholder: "v2.6.0"
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - OS: Ubuntu 22.04
        - .NET Version: 8.0
        - Broker: Binance Testnet
        - Docker: Yes/No
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output (if applicable)
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: Screenshots, error messages, etc.
    validations:
      required: false
