blank_issues_enabled: true
contact_links:
  - name: Ask a Question
    url: https://github.com/kenyboi/AlgoTrendy/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/kenyboi/AlgoTrendy/blob/main/README.md
    about: Read the project documentation
