name: Feature Request
description: Suggest a new feature for AlgoTrendy
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details below.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Explain the problem this feature would solve
      placeholder: |
        What problem does this solve?
        Who would benefit from this feature?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How you envision this feature working
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this affect?
      options:
        - Trading Engine
        - Data Channels
        - Brokers
        - Strategies
        - API
        - Backtesting
        - Frontend
        - Infrastructure
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my work)
        - High (needed soon)
        - Medium (nice to have)
        - Low (future consideration)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you've thought about
      placeholder: Describe alternative solutions...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Links, mockups, examples from other projects, etc.
    validations:
      required: false
