global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'algotrendy-monitor'

# Scrape configurations
scrape_configs:
  # AlgoTrendy API metrics
  - job_name: 'algotrendy-api'
    static_configs:
      - targets: ['api:5000']
    metrics_path: '/api/metrics/prometheus'
    scrape_interval: 10s

  # System metrics (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Container metrics (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
